# Generated by Django 4.2 on 2023-05-24 08:39

import datetime
import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("borrowings", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="borrowing",
            name="actual_return_date",
            field=models.DateField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(datetime.date(2023, 5, 24))
                ],
            ),
        ),
        migrations.AlterField(
            model_name="borrowing",
            name="borrow_date",
            field=models.DateField(
                default=django.utils.timezone.now,
                validators=[
                    django.core.validators.MinValueValidator(datetime.date(2023, 5, 24))
                ],
            ),
        ),
        migrations.AlterField(
            model_name="borrowing",
            name="expected_return_date",
            field=models.DateField(
                default=django.utils.timezone.now,
                validators=[
                    django.core.validators.MinValueValidator(datetime.date(2023, 5, 24))
                ],
            ),
        ),
    ]
